### ISSUE TITLE
Show last 10 files updated (like Global Changes in web UI)?

### ISSUE THREAD

**Issue by TRSx80** [serl/syncthing-quick-status#2]
Very handy little script you have here! Thank you for sharing it!

I also spend a lot of time in the terminal, and running this is much faster than waiting for Firefox to load all that Javascript...

One feature I was missing though was the ability to see the last several files that were synced. I guess I'm paranoid; when I change a file, I like to have positive confirmation of it's propagation before I start editing he same file from a different device. :)

I went digging through the Syncthing API documentation, but I couldn't seem to figure it out (yet). Maybe I will have another try some time.

Until then, I thought I would make a post, in case you or anyone else might be missing the same functionality. I would even be appreciative of a hint on what to look for, or how to implement such a thing. If I get it working I would be happy to submit a PR, of course.

**Comment by serl** [comment]
Hello,
it makes perfectly sense! I found the api, it is `/events/disk?limit=X` to have the X latest events.
I'm writing something right now ;)

**Comment by serl** [comment]
...let me know if you'd change something for the output format ;)

**Comment by TRSx80** [comment]
Looks great @serl! Thank you!

I actually logged in today to Github for something else, but yesterday had already noticed the change when installing / running sqs for the first time from a newly set up computer.

Cheers! :)
