### ISSUE TITLE
Failed Items are not shown

### ISSUE THREAD

**Issue by thomasmerz** [serl/syncthing-quick-status#7]
@serl 

When there are "failing items" in Syncthing's WebGUI for one or more folder(s) your script doesn't show us that are "failing items" in output:

```
T_dev (hourly): up to date
```
<img width="344" alt="image" src="https://user-images.githubusercontent.com/18568381/153464610-d888c22c-56f3-4839-b588-94bf12335ba0.png">

vs.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/18568381/153463412-09dad5ee-4b78-4dac-9a34-58cbb39a6421.png">

---

Only optional '-v' parameter gives us some hints that there are some problems :
```
Last log entries:
2022-02-10T18:19:58 Scanner (folder "T_dev (hourly)" (T_dev), item "docker-speedtest-tracker/log/php/error.log.1"): hashing: open /home/thomas/dev/docker-speedtest-tracker/log/php/error.log.1: permission denied
```

----

Your script should
- show that there are "failing items",
- automatically switch to "verbose" mode or tell us that we will get more/detailled information with  "verbose" mode (optionally 😉).

**Comment by serl** [comment]
Should be fixed now. Let me know if it works as expected :)

**Comment by thomasmerz** [comment]
This is much better than before and even great without my optional proposal of an automatic "-v" parameter (or: show last log entries) if failed items are detected:
```
T_Downloads: 1 failed items
…
Last log entries:
2022-02-13T22:19:33 Scanner (folder "T_Downloads" (Downloads), item "ROOTOOOOT"): hashing: open /home/thomas/Downloads/ROOTOOOOT: permission denied
```
